### ISSUE TITLE
WSL

### ISSUE THREAD

**Issue by guillaumejchauveau** [UFRCaenDiscordServer/guide-du-petit-informaticien#1]
Il faudrait absolument parler du WSL de windows qui a complètement retourné le game pour moi. Avant j'ai un argument pour retourner sous Linux (j'ai fait Vista->Ubuntu->Fedora->Windows 10) mais depuis le WSL je n'ai aucuns intérêts à y aller ce truc est une merveille. Le grand truc qui m'a convaincu c'est les permissions Unix virtuelles sur les drives windows (que j'e n'avais pas avec une machine virtuelle par exemple). Ça posait pleins de problèmes par exemple le dossier .ssh qui était automatiquement en 777 ce qui empêchait son utilisation. Et enfin le fait que les 2 systèmes puissent communiquer aussi facilement est un vrai plaisir: j'utilise Kleopatra pour gérer mes clefs PGP sous windows eh ba avec un alias je peux l'utiliser aussi dans le WSL sans problèmes. Le seul truc un peu limitant est pour les logiciels windows qui ont besoin d’accéder a l’exécutable (un IDE par exemple). Il faut aller chercher dans Appdata\Local\Packages\... et il me semble que le dossier peut changer de nom en cas de mise à jour dans le store. J'ai trouvé plus simple d'installer une version Windows du logiciel: j'ai eu le problème pour Git, des versions différentes importent peu (surtout que la version windows est plus récente que les packages debian ^^). Il faut par contre les droits d'administration pour activer le sous-système.

**Comment by helldragger** [comment]
Pour le coup je n'ai jamais utilisé le WSL et ne le connais pas assez pour résumer dans avoir peur de dire des bétises, pourrais tu me faire un mini résumé que je puisse l'ajouter à la page des bases?
